1inch/solidity-utils

contracts/libraries/ECDSA.sol

At the cost of 2 extra runtime gas we get output size validation check. By spec the function should return abi-encoded 4-byte selector which is 32 bytes of data.

add more correctness to isValidSignature

---

.github/workflows/publish.yml
.gitignore
package.json

Investigated `package.json` scripts lifecycles:
- npm: https://docs.npmjs.com/cli/v9/using-npm/scripts#npm-pack  
- yarn: https://yarnpkg.com/advanced/lifecycle-scripts  Gtht
Decided the following:
- Use `prepack` for `clean` and `build`
- Use `build` for `typechain` and TS compilation
- Use `clean` for cleaning Solidity and JS related artifacts

Improve package.json scripts

---

README.md
hardhat.config.ts
hardhat.networks.ts
package.json
src/prelude.ts
src/utils.ts
test/utils.test.ts
yarn.lock

Added function `deployAndGetContract` to `src/utils.ts`.
This function uses the `deploy` function from the `hardhat-deploy` plugin and verifies contract on Etherscan afterwards if requested.

[SC-846] Extract deploy helper implementations to solidity-utils

---

package.json
src/utils.ts

There is local nodes (like zksync) which return promise's result with await before blockchain state changed.
It works correct when we check `postBalance` after `await txResult.wait();`

Patch trackReceivedTokenAndTx method

---

hardhat-setup/networks.ts
package.json

--
Migrate deprecated zkSync Goerli testnet to the new zkSync Sepolia testnet, because Goerli was sunseted on March 31st.
--
--

[SC-1116] Change zksync testnet network

---

contracts/tests/mocks/Create3Mock.sol
docs/js/classes/hardhat_setup.Networks.md
docs/js/enums/src.NonceType.md
docs/js/interfaces/src.DeployContractOptions.md
docs/js/interfaces/src.SignedCallStruct.md
docs/js/modules/hardhat_setup.md
docs/js/modules/src.md
package.json
src/utils.ts
test/utils.test.ts
yarn.lock

Added a method to save a deployment object after deploying via create3, as `hardhat-deploy` does not support this and contracts deployed via create3 remain without deployments or with outdated ones. This method allows saving up-to-date deployment information.
The new method is similar to the `deployAndGetContract` method and is intended for deploying contracts and verifying code, but using for deploy with create3. It provides similar interaction flows and interacts with external APIs in a comparable manner.
Efficiency has not been measured as this is an auxiliary JS utility without EVM optimizations. The focus was on functionality and ease of use.
- The method creates a deployment object useful for further use and analysis. This facilitates the management and tracking of deployed …

[SC-1177] Deploy with create3 and save deployment

---

contracts/libraries/ECDSA.sol
package.json

- This makes sure the commented solidity code accurately reflects what is being done in assembly.

Fix comment in ECDSA.sol

---

package.json
src/utils.ts
test/utils.test.ts

It's good enough readable and compact check.
By default the check is switched on to protect developer from prevent unnecessary redeployment of already deployed contracts. Allows to customize this setting status as needed.
No impact on gas costs and computational complexity.
This addition is a straightforward and effective way to enhance deployment logic, with minimal trade-offs. It ensures that resources are used more efficiently without adding significant complexity to the codebase.

[SC-1242] skipIfAlreadyDeployed in deploy method via create3

---

contracts/mixins/PermitAndCall.sol
docs/contracts/mixins/PermitAndCall.md
package.json
src/utils.ts

chore: fix some typos

---

docs/js/hardhat-setup/classes/Networks.md
hardhat-setup/README.md
hardhat-setup/networks.ts
package.json

Code is readable and compact, with consistent naming.
Updated zkSync network integration to enable contract verification on an Etherscan-like explorer.
No runtime impact, documentation-only.
Enhances onboarding and maintainability.

[SC-1343] Update zkSync verification to use an Etherscan-like explorer

---

contracts/libraries/SafeERC20.sol
package.json
test/contracts/SafestERC20.test.ts

The changes improve readability by enforcing a consistent code style across the project. This ensures that the code is easier to follow and maintain, reducing cognitive load for developers. Compactness is not directly impacted but benefits from uniform formatting.
No changes to external API interactions or execution flows. This update is limited to static style adjustments and does not alter runtime behavior.
No impact on efficiency. The changes do not affect gas costs, computational complexity, or memory usage, as they are purely stylistic.
Using a consistent code style improves collaboration and reduces the potential for merge conflicts caused by formatting differences.

[SC-1387] Use a consistent code style

---

hardhat-setup/networks.ts
package.json

Added a temporary solution by manually specifying the hardforkHistory property in Hardhat configuration to fix forking issue for Avalanche networks (the same as https://github.com/NomicFoundation/hardhat/issues/5511) until a [fix](https://github.com/NomicFoundation/hardhat/pull/6170) is implemented in Hardhat.
- The solution is straightforward and does not introduce significant complexity.
- The added configuration is clear and maintains code readability.
- The fix relies on manually estimated block numbers based on timestamps from the blog:
- ACP-24 (Shanghai): [December 22nd, 2022, at 6:42:29 AM UTC](https://www.avax.network/blog/durango-avalanche-warp-messaging-comes-to-the-evm)
- ACP-131 (Cancun): [December 16th, 2024, at 5 PM …

[SC-1394] Fix avax forking issue

---

contracts/libraries/SafeERC20.sol
contracts/libraries/UniERC20.sol
package.json

The removal of the fixed gas limitation. The logic remains straightforward and functional while improving compatibility with L2 solutions such as zkSync, where gas requirements can be unpredictable.
The previous fixed gas limit of 5000 units posed challenges in zkSync environments, where certain operations require more gas than initially anticipated. Although the contracts compiled successfully, runtime failures occurred in production due to insufficient gas allocation. By removing the arbitrary gas cap, the contract can now better handle interactions with zkSync and other L2 solutions, ensuring more reliable and adaptable execution.
Allowing the call to use the full available gas improves the reliability of transactions by reducing the likelihood of failures caused by gas constraints. …

[SC-1387] Remove gas usage limitation by using all available gas

---

src/utils.ts

Improved logic flow, ensuring deployment saving before contract source code verification process.
Contract source code verification failure no longer interrupts deployment saving.
No impact on gas costs or complexity. Execution order changed but overall efficiency remains the same.
Ensures deployment persistence even if verification fails, improving reliability.

[SC-1435] Fix Create3 deployment saving on contract source code verification failure

---

src/permit.ts

Code remains clear and concise, improving maintainability by adding explicit chain-based logic.
Ensures correct Permit2 address selection based on chainId, improving compatibility with different networks.
No significant impact on performance as the changes involve static lookups and minimal computation.
Enhances flexibility with minimal code changes; future networks may require minimal updates.

[SC-1426] Add `permit2address` method and patch `permit2Contract` method with `chainId`

---

contracts/libraries/SafeERC20.sol
package.json

Added helper method `getPermit2Address` to avoid breaking changes by selecting the appropriate constant based on chainId for zkSync and other networks.
Improves flexibility without modifying existing logic.
Ensures correct `Permit2` contract address selection per supported network.
Minimal gas overhead with conditional logic.
- Maintains backward compatibility while adding multi-chain support.
- Easy to add different custom networks in the future.

[SC-1426] Permit2 for zksync

---

.github/workflows/release.yml
CHANGELOG.md
changelog/changelog-template.hbs
docgen/index.ts
package.json
yarn.lock

- The changelog format is well-structured and easy to read.
- The CI configuration is compact and maintains clarity.
The CI workflow automates release creation with changelog verification.
The implementation minimizes redundant steps and optimizes execution time.
Looks usefull, should be added.

[SC-1427] Add Change Log and CI for release 

---

CHANGELOG.md
hardhat-setup/networks.ts
package.json
yarn.lock

Removed redundant chains default - cleaner config after upstream fix.
No impact - config only.
No runtime effect.
Hardhat update resolved prior issue; patch no longer needed.

[SC-1454] Remove temporary chains patch

---

package.json
src/utils.ts
test/utils.test.ts

- Added `getAccountsWithCode()` utility for reuse across tests
- Simplifies setup logic and reduces code duplication
- Ensures test accounts are in a clean state by resetting code to '0x'
- Avoids issues with EIP-7702 forwarding contracts on default accounts
- Supports setting custom bytecode per account when needed
- Runs only in test environments, no impact on production
- Negligible overhead in test setup
- Might generalize further if more bytecode cases appear

[SC-1479] Normalize test accounts to empty code state

---

hardhat-setup/networks.ts
package.json

- Introduced an `autoLoadEnv` flag in the `Networks` constructor to control whether environment variables should be automatically loaded via `dotenv.config()`. 
- Added a `loadEnv()` utility function that loads environment variables, by default from `.env`, but accepts standard `dotenv.config` options (e.g., custom path or encoding). 
These changes remove hidden side effects, improve clarity, and preserve backward compatibility.
Previously, environment variables were always loaded implicitly during `Networks` instantiation, which could lead to issues if `process.env` was accessed before that (e.g., in `hardhat.config.ts`). The new approach allows developers to load environment variables explicitly using `loadEnv(options?)` at the appropriate point in the setup flow.
No impact. The change …

[SC-1504] Make `.env` loading optional with `autoLoadEnv` constructor flag

---

hardhat-setup/networks.ts
package.json

Clear and concise - removes unused code, improves maintainability.
No way to use `fantom`, `aurora`, `klaytn` networks because it was deprecated.
Slight improvement - less config overhead, lower memory footprint.
Good cleanup, no downsides.

[PT1-156] Remove deprecated networks: `fantom`, `aurora`, `klaytn`

---

hardhat-setup/README.md
hardhat-setup/networks.ts

Replaces Etherscan API network keys with a single v2 key. Config is simpler and easier to maintain.
Switches verification to Etherscan API v2.
Breaking: requires a new unified env var `ETHERSCAN_API_KEY` for method `registerAll()` for the API V2 key. API V1 keys no longer work (Etherscan sunset).
No runtime impact, configuration-only change.
Breaking in contract source verifications (and deploys with verification) but necessary.

[PT1-153] Update hardhat config for Etherscan API v2 from deprecated v1 (env change required)
